dist: trusty
language: ruby
rvm:
  - 2.3.1
env:
  - PARITY="1.5.0"
  - PARITY="1.5.7"
cache:
  bundler: true
  directories:
  - ~/.parity
before_install:
  - sudo bin/install_parity
  - gem install bundler -v 1.11.2
before_script:
  - parity --warp --chain testnet -d ~/.parity --password ~/.parity/pass --unlock 3089630d06fD90Ef48a0c43f000971587c1F3247 --author 3089630d06fD90Ef48a0c43f000971587c1F3247 daemon ~/.parity.pid --log-file ~/.parity.log
  - cat ~/.parity.log
  - sleep 5
  - parity --chain testnet account list
  - cat ~/.parity.log
  - bundle exec rake ethereum:node:waitforsync
script:
  - bundle exec rspec --tag ~blockchain && bundle exec rspec --tag blockchain
before_cache:
  - killall parity
  - sleep 3
after_script:
  - cat /tmp/ethereum_ruby_http.log
