dist: xenial
language: ruby
rvm:
  - 2.4.3
  - 2.5.0
  - 2.6
  - 2.7
env:
  - PARITY="2.5.12"
cache:
  bundler: true
  directories:
  - ~/.parity
before_install:
  - sudo bin/install_parity
  - gem update --system
  - gem install bundler
before_script:
  - ./parity --warp --chain dev --password ~/.devpass --unlock 00a329c0648769a73afac7f9381e08fb43dbea72 --author 00a329c0648769a73afac7f9381e08fb43dbea72 daemon ~/.parity.pid --log-file ~/.parity.log
  - sleep 5
  - ./parity --chain dev account list
  - cat ~/.parity.log
script:
  - bundle exec rspec --tag ~blockchain && bundle exec rspec --tag blockchain
before_cache:
  - killall parity
  - sleep 3
after_script:
  - cat /tmp/ethereum_ruby_http.log
notifications:
  slack:
    secure: is1TFfNJTX4VsDTu3zC5vIZ+Cowj0fQDFyqHPYxvuX60NHh8WBrjZ1qwnehTlLtC6d58EByxr+KVChCxrRdZ6IenpdXq+2Oz4IRS5I8tkvFbc8o30weBd7Umw3MzwTdSdoV0jQsyy395jYr3cxzJCBt+7tJRA93V8tN6yiHe8w7ImY3R20HKtLuE3ZWh3gjrAVx3u9fEolNBIuQvWl1jMl23ptizoHuesMCYgeehdtPxxOq/smKWN6Ds30hDG16lfEtSm8jxNjepMYZ/zGcHB/DCCRBgo5wHMmLzjCHL5mzf5YDr47gAtywXT7zpdMGbMep8H/QRR9kkCmp5o1FUzHx1CjFHIHCngwawBz6oy3/3jDIuLa3Z+SYHxbDHYZ3Xb8UKDrHl7IKF2dQ5fQRoxpaQ4mMAHbIQDyWp9kRwLljAX6cBDDjGF6/+TCn/BUE+KQZupBG79KymoFZlH7TYyKofHvcp7dcfSFyF8XKsHUglDSmISERbt/KN9zP2876o1ZDt+4HOzGM0lW6Z0nibhTdLHmzrA2fdxGpsJY7Eh6j9h7imgXP7rfCcXb3c4ib+XU1B2S1clmdyj/+03V+wLhvUqse5pBbQqTogr92gziLGKhDGBk4zz0q1a4D4y0qe79AA79R14VbdYC23+nehvpSW8gANfN4IcuX9srBCJjY=
